### ISSUE TITLE
Can't run terraform destroy on workers been rebooted

### ISSUE THREAD

**Issue by simox-83** [lander2k2/kube-cluster#6]
If we reboot the worker instances for any reasons and then trying to destroy the cluster, when running ```terraform destroy``` on the worker.tf we get an error message:

```Error: Error refreshing state: 1 error(s) occurred:

* data.local_file.user_data: 1 error(s) occurred:

* data.local_file.user_data: data.local_file.user_data: open /tmp/kube-workers/worker-bootstrap.sh: no such file or directory
```
Can't we just upload that script somewhere else?
Thanks!

**Comment by edtoon** [comment]
The script isn't "uploaded" to that path - it's read *from* that path on the machine that Terraform is running on, I assume as a quick workaround to Terraform's weird user_data behavior. That will have to be handled differently in order to avoid this error.

(See https://github.com/hashicorp/terraform/issues/145 for more about the "weirdness", it should be fixed now...)

**Comment by lander2k2** [comment]
@edtoon is correct.  The file `/tmp/kube-workers/worker-bootstrap.sh` is created on the local machine during cluster installation.  `kube-cluster.sh` generates that file when masters are created.  Then it is referenced when the worker ASG is created.

@simox-83 Have you tried creating an empty file at `/tmp/kube-workers/worker-bootstrap.sh`?  Since you're destroying, it shouldn't matter that it doesn't have the correct content.

**Comment by simox-83** [comment]
@lander2k2 Thanks for your suggestion. I tried to do what you suggested and it works. Thanks for the clarifications too @edtoon
